### PR TITLE
Support Sprite Frames individual Frame Duration multiplier

### LINKED ISSUE #5: SpriteFrames individual frame duration is not honored in resulting animation
# Context

I need to add some lag at the beginning of my attack animation for telegraphing, but since I'm using a spritesheet made by someone else, I cannot just draw my own extra sprites, so I'm just extending the duration of the first frames.

To do this, there are three ways:
a. on the SpriteFrames, increase the Frame Duration setting of individual sprites (what we are interested in here)
b. on the SpriteFrames, add copies of the same sprites after itself
c. on the resulting AnimationPlayer animation, move the sprite keys after the sprite to extend later in the timeline

# Issue

With method a., I noticed that the resulting animation still gives the same duration to every sprite frame, ignoring the Frame Duration setting.

Sprite Frames setup:
image

Resulting animation:
image

# Request

When pressing Import, we should multiply the duration of a sprite frame in the resulting animation by Frame Duration.

# Workaround

As a fallback, I tried method b., which works, but has two disadvantages:
1. There is no "Duplicate after" button so it's cumbersome to add extra copies of the same frame: you must copy-paste it but the pasted frame is added to the end of the SpriteFrames, so you must then move it left repeatedly until it reaches the same place as the original frame.
2. You can only multiply the total duration of the sprite by an integer number this way, equal to the number of identical sprites. Whereas Frame Duration allows fractions like x2.5.

As a second fallback, I tried method c., which works, but next time I press the Import button, it will replace my adjusted animation and all sprites will revert to having the same duration. Plus, the old "don't replace" mode from Godot 3 version has been removed, so I don't have a way to prevent overwriting my custom changes while still adding new animations (it would be useful to combine the old and new behavior with a hybrid mode "don't replace existing tracks" for these situations; but that would be the topic of another issue for proposal).

### PR DESCRIPTION
**Pull request by hsandt**
For demonstration, set the Frame Duration of the first two frames of the attack animation to x1.5

Fixes #5

### CODE REVIEW

**Comment by hsandt** [comment]
As a side note, I tried to keep whitespaces in big blocks but not between big blocks. However the formatting rule is not too clear. May I strip all whitespaces next time, using the text_editor/behavior/files/trim_trailing_whitespace_on_save setting?

**Comment by poohcom1** [comment]
Dang, that was fast! Thanks, I'll take a look. 

For the formatting, you can go just ahead and strip, I think that'll be better too.

**Comment by poohcom1** [comment]
LGTM! I'll merge now so I can update the addon on the asset library as soon as possible. 

As for the formatting, you can create another PR or just wait until next time. I'll actually add you as a collaborator since you've contributed a lot and you probably use this addon more than me now xD. If are okay with that, then you're free to format or add other features (or still create PRs if you prefer).

**Comment by hsandt** [comment]
Thanks, I accepted the invite. I'll format next time I do some changes.

You're right, I'm using the importer a lot, it really improves my workflow when working directly from a spritesheet and tuning the FPS. If I have an idea for another feature (like hybrid track preserve mode), I'll open an issue and start working on it.

**Pull request merged**
